CREATE DATABASE meubles;
\c meubles;



CREATE SEQUENCE seq_materiel START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_style START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_style_materiel START WITH 1 INCREMENT BY 1;



